### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError

### ISSUE THREAD

**Issue by niners52** [ydenyshchenk/Sparta_UrlRewriteRebuilder#3]
I downloaded and installed the module. When I try and run it I get this error- 

php bin/magento sparta:rebuild:rewrite -vvv
[STEP 1] Truncating table `catalog_url_rewrite_product_category` and deleting auto-generated `url_rewrite`... performed successfully in 00:00:00
[STEP 2] Rebuilding URL rewrites for CMS pages... PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Magento\CatalogUrlRewrite\Model\Category\Plugin\Storage::afterReplace() must be of the type array, null given, called in /chroot/home/wolfauto/wolfautomation.com/html/vendor/magento/framework/Interception/Interceptor.php on line 146 and defined in /chroot/home/wolfauto/wolfautomation.com/html/vendor/magento/module-catalog-url-rewrite/Model/Category/Plugin/Storage.php:45
Stack trace:
#0 /chroot/home/wolfauto/wolfautomation.com/html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\CatalogUrlRewrite\Model\Category\Plugin\Storage->afterReplace(Object(Sparta\UrlRewriteRebuilder\Model\DbStorage\Interceptor), NULL, Array)
#1 /chroot/home/wolfauto/wolfautomation.com/html/vendor/magento/framework/Interception/Interceptor.php(153): Sparta\UrlRewriteRebuilder\Model\DbStorage\Interceptor->Magento\Framework\Interception\{closure}(Array)
#2 /chroot/home/wolfauto/wolfautomation.com/html/generated/code/Sparta/UrlRewriteRebuilder/Model/DbStorage/Interceptor.php(26):  in /chroot/home/wolfauto/wolfautomation.com/html/vendor/magento/module-catalog-url-rewrite/Model/Category/Plugin/Storage.php on line 45

Any Ideas?

Edit: I would liked to add that I cleared the generated and var folder and ran di compile afterwards.

Edit: Want to add that I am using 2.2.6 as well

**Comment by ydenyshchenk** [comment]
Fixed in https://github.com/ydenyshchenk/Sparta_UrlRewriteRebuilder/tree/2.2.6
